---
name: Log-Procmail
version: 0.11
author:
  - Philippe "BooK" Bruhat <book@cpan.org>
abstract: Perl extension for reading procmail logfiles.
license: perl
requires:
  Test::More: 0
provides:
  Log::Procmail:
    file: lib/Log/Procmail.pm
    version: 0.11
  Log::Procmail::Abstract:
    file: lib/Log/Procmail.pm
    version: 0.11
generated_by: Module::Build version 0.26
