---
abstract: 'Perl extension for reading procmail logfiles.'
author:
  - "Philippe \"BooK\" Bruhat <book@cpan.org>"
build_requires: {}
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Log-Procmail
provides:
  Log::Procmail:
    file: lib/Log/Procmail.pm
    version: 0.12
  Log::Procmail::Abstract:
    file: lib/Log/Procmail.pm
    version: 0
requires:
  Test::More: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/book/Log-Procmail
version: 0.12
